export const AQTags = {
  ALL: "all",
  CATEGORY: "category",
  BRAND: "brand",
  PRODUCT: "product",
  MEDIA: "media",
  USER: "user",
  CURRENT_USER: "current-user",
  IS_USER_LOGGED_IN: "is-user-logged-in",
  BRANCH: "branch",
  SETTINGS: "settings",
  REVIEW: "review",
  SHIPPING_ADDRESS: "shipping-address",
  ORDER: "order",
};
